name: TestPlugin
version: '${project.version}'
main: com.habu.testplugin.TestPlugin
api-version: '1.19'
commands:
  shopnpcapply:
    description: apply shop function to npc
  check:
    description: 수표 발행
    aliases: 수표
  statcheck:
    description: statcheck
  switchcheckblock:
    description: turn on/off block id Check
  goldsetplayer:
    description: set player gold
  goldaddplayer:
    description: add player gold
  jobsetplayer:
    description: set player job
  titlesetplayer:
    description: set player title
  mycoin:
    description: 코인 개수 확인
    aliases: 코인
  calloperator:
    description: 운영자 호출
    aliases: 호출